apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-ingress
  namespace: reservas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: reservas.local
      http:
        paths:
          - path: /(graphql)
            pathType: ImplementationSpecific
            backend:
              service:
                name: booking-service
                port:
                  number: 5000
          - path: /(health)
            pathType: ImplementationSpecific
            backend:
              service:
                name: booking-service
                port:
                  number: 5000
