apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
  namespace: reservas
  labels:
    app: booking-service
    tier: backend
    component: secret
type: Opaque
data:
  POSTGRES_PASSWORD: Ym9va2luZw==
  JWT_SECRET: c2VjcmV0by1zdXBlci1zZWd1cm8=
